services:
  document-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-document:/var/opt/mssql
  occurrence-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-occurrence:/var/opt/mssql
  short-word-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data-short:/var/opt/mssql
  medium-word-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data-medium:/var/opt/mssql
  long-word-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data-long:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: WordSearcher/Dockerfile
    deploy:
     replicas: 3
    depends_on:
     - word-db
  console:
    build:
      context: .
      dockerfile: ConsoleSearch/Dockerfile
    deploy:
     replicas: 3
    depends_on:
     - api
  indexer:
    build:
      context: .
      dockerfile: Indexer/Dockerfile
    deploy:
     replicas: 3
    depends_on:
     - api
  
volumes:
  mssql-data-short:
  mssql-data-medium:
  mssql-data-long:
  mssql-document:
  mssql-occurrence: 

